databases:
  - name: BudgetApp
    databaseName: budget_app_development
    user: <%= ENV["DATABASE_URL"] %>

services:
  - type: web
    name: BudgetApp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV["DATABASE_URL"] %>
        fromDatabase:
          name: BudgetApp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false